#!/usr/bin/env python
#=========================================================================
# sort-xcel-sim [options]
#=========================================================================
#
#  -h --help           Display this message
#
#  --impl              {fl,cl,rtl}
#  --input <dataset>   {random,sorted-fwd,sorted-rev}
#  --trace             Display line tracing
#  --stats             Display statistics
#  --translate         Translate RTL model to Verilog
#  --dump-vcd          Dump VCD to sort-xcel-<impl>-<input>.vcd
#  --dump-vtb          Dump a SystemVerilog test harness
#
# Author : Christopher Batten
# Date   : March 16, 2015
#

# Hack to add project root to python path

import os
import sys

sim_dir = os.path.dirname( os.path.abspath( __file__ ) )
while sim_dir:
  if os.path.exists( sim_dir + os.path.sep + "pymtl.ini" ):
    sys.path.insert(0,sim_dir)
    break
  sim_dir = os.path.dirname(sim_dir)

import argparse
import re
import struct

from random import randint

from pymtl3 import *
from pymtl3.stdlib.test_utils import config_model_with_cmdline_opts
from pymtl3.passes.backends.verilog import VerilogPlaceholderPass

from lab2_xcel          import SortXcelFL
#from lab2_xcel          import SortXcelCL
from lab2_xcel          import SortXcelRTL
from proc.XcelMsg       import *

from lab2_xcel.test.SortXcelFL_test import TestHarness, large_data, sort_fwd_data, sort_rev_data, gen_xcel_protocol_msgs

#-------------------------------------------------------------------------
# Command line processing
#-------------------------------------------------------------------------

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print("\n ERROR: %s" % msg)
    print("")
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print( line[1:].rstrip("\n") )

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-h", "--help",    action="store_true" )

  # Additional commane line arguments for the simulator

  p.add_argument( "--impl", default="fl", choices=["fl","cl","rtl"] )

  p.add_argument( "--input", default="random",
    choices=["random","sorted-fwd","sorted-rev"] )

  p.add_argument( "--trace",     action="store_true" )
  p.add_argument( "--stats",     action="store_true" )
  p.add_argument( "--translate", action="store_true" )
  p.add_argument( "--dump-vcd",  action="store_true" )
  p.add_argument( "--dump-vtb",  action="store_true" )

  opts = p.parse_args()
  if opts.help: p.error()
  return opts

#-------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------

def main():
  try:
    import pypyjit
    pypyjit.set_param("off")
  except:
    pass

  opts = parse_cmdline()

  # Create the input pattern

  data = None

  if   opts.input == "random":     data = large_data
  elif opts.input == "sorted-fwd": data = sort_fwd_data
  elif opts.input == "sorted-rev": data = sort_rev_data

  ninputs = len(data[::2])

  # Determine which model to use in the simulator

  model_impl_dict = {
    "fl"  : SortXcelFL,
#    "cl"  : SortXcelCL,
    "rtl" : SortXcelRTL,
  }

  # Check if translation is valid

  if opts.translate and not opts.impl.startswith("rtl"):
    print("\n ERROR: --translate only works with RTL models \n")
    exit(1)

  # Convert test data into byte array

  data_bytes = struct.pack("<{}I".format(len(data)),*data)

  # Protocol messages

  xcel_protocol_msgs = gen_xcel_protocol_msgs( 0x1000, len(data) )

  # Create test harness (we can reuse the harness from unit testing)

  th = TestHarness( model_impl_dict[ opts.impl ]() )

  # Load the data

  th.set_param("top.src.construct",  msgs=xcel_protocol_msgs[::2] )
  th.set_param("top.sink.construct", msgs=xcel_protocol_msgs[1::2] )

  # Create VCD filename

  unique_name = f"sort-xcel-{opts.impl}-{opts.input}"

  cmdline_opts = {
    'dump_vcd': f"{unique_name}" if opts.dump_vcd else '',
    'dump_vtb': f"{unique_name}" if opts.dump_vtb else '',
    'test_verilog': 'zeros' if opts.translate else '',
    'test_yosys_verilog': '',
    'dump_textwave': '',
  }

  # Configure the test harness component

  config_model_with_cmdline_opts( th, cmdline_opts, duts=['xcel'] )

  # Load the data into the test memory

  for i in range( len(data) ):
    th.mem.write_mem( 0x1000, data_bytes )

  # Apply necessary passes

  # Create a simulator
  th.apply( DefaultPassGroup( linetrace=opts.trace ) )

  # Reset test harness

  th.sim_reset()

  # Run simulation

  while not th.done():
    th.sim_tick()

  # Extra ticks to make VCD easier to read

  th.sim_tick()
  th.sim_tick()
  th.sim_tick()

  # Retrieve data from test memory

  result_bytes = th.mem.read_mem( 0x1000, len(data_bytes) )

  # Convert result bytes into list of ints

  result = list(struct.unpack("<{}I".format(len(data)),bytearray(result_bytes)))

  # Compare result to sorted reference

  assert result == sorted(data)

  # Display statistics

  if opts.stats:
    print( f"num_cycles = {th.sim_cycle_count()}" )

main()
